[project]
description = "Retrieve Bible sections from an org-mode file."
authors = [ { name="John C G Sturdy", email="jcg.sturdy@gmail.com" } ]
readme = "README.md"
license = "GPL-3.0-or-later"
name = "orgbookchapterverse"
version = "0.1.1"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
